"""Data model definitions for the DataPool.

The DataPool stores rollout trajectories at Step granularity. A Step is the atomic
(state, action, reward) unit in the RL sense. Trajectories and prompt groups are
reconstructed from Step metadata fields rather than nested data structures.
"""

from dataclasses import dataclass
from typing import Any, Optional

from verl.base_config import BaseConfig


@dataclass
class Step:
    """Atomic storage unit in the DataPool — one (state, action, reward) tuple.

    In the LLM context:
    - state  = prompt_ids (the full context up to this point)
    - action = response_ids (purely LLM-generated tokens)
    - reward = the immediate reward for this step

    Steps belonging to the same trajectory share a ``trajectory_uid`` and are
    ordered by ``step_index``. Steps whose trajectories originate from the same
    prompt share a ``prompt_uid`` (used for GRPO-style group advantage).
    """

    prompt_ids: list[int]
    """State — token IDs of the full context preceding LLM generation."""

    response_ids: list[int]
    """Action — token IDs generated by the LLM (every token receives policy gradient)."""

    reward: Optional[float] = None
    """Immediate reward for this step."""

    multi_modal_data: Optional[dict[str, Any]] = None
    """Multi-modal data."""

    rollout_log_probs: Optional[list[float]] = None
    """Per-token log pi_rollout(a|s). Used for off-policy correction and bypass mode."""

    routed_experts: Any = None
    """MoE routing decisions per token. Used for auxiliary load-balancing loss."""

    trajectory_uid: str = ""
    """Unique ID of the trajectory this step belongs to."""

    prompt_uid: str = ""
    """ID of the originating prompt (shared across n rollouts for GRPO grouping)."""

    step_index: int = 0
    """Position of this step within its trajectory (0-indexed)."""

    policy_version: int = 0
    """Version of the policy that generated this step (for off-policy staleness detection)."""

    is_last: bool = False
    """Whether this is the final step of the trajectory."""

    metadata: Optional[dict[str, Any]] = None
    """Optional dataset metadata (data_source, reward_model, uid, etc.).

    Carried alongside the Step so the Trainer can compute rewards without
    needing the original dataset batch.  VerlBackend expands these fields
    into ``non_tensor_batch`` of the output ``DataProto``."""


@dataclass
class DataPoolConfig(BaseConfig):
    """Configuration for the DataPool.

    Args:
        n_rollouts (int): Number of rollout trajectories per prompt.
        scheduling_policy (str): Scheduling policy for fetch_batch ordering.
    """

    n_rollouts: int = 1
    scheduling_policy: str = "fifo"
